# Generated by Django 5.0.6 on 2024-07-02 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carpet',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='carpet',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='material',
            field=models.CharField(choices=[('wool', 'Wool'), ('silk', 'Silk'), ('synthetic', 'Synthetic'), ('cotton', 'Cotton'), ('jute', 'Jute'), ('viscose', 'Viscose'), ('polypropylene', 'Polypropylene'), ('polyester', 'Polyester'), ('acrylic', 'Acrylic'), ('leather', 'Leather'), ('natural_fiber', 'Natural Fiber'), ('blend', 'Blend')], max_length=100),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='pattern',
            field=models.CharField(choices=[('oriental', 'Oriental'), ('modern', 'Modern'), ('floral', 'Floral'), ('geometric', 'Geometric'), ('solid', 'Solid'), ('striped', 'Striped'), ('abstract', 'Abstract'), ('shag', 'Shag'), ('animal_print', 'Animal Print'), ('southwestern', 'Southwestern'), ('moroccan', 'Moroccan'), ('chevron', 'Chevron'), ('paisley', 'Paisley'), ('damask', 'Damask'), ('ikat', 'Ikat'), ('trellis', 'Trellis'), ('tribal', 'Tribal'), ('vintage', 'Vintage'), ('bohemian', 'Bohemian'), ('coastal', 'Coastal'), ('traditional', 'Traditional')], max_length=100),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='pile_height',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='carpetreview',
            unique_together={('carpet', 'user')},
        ),
    ]
